"""
CLI orchestrator – wires git data collection → Markdown newsletter.

This module is used by the ``python -m newsletter`` CLI only.  It has no
dependency on a Python session database; all state is plain dicts kept in
memory for the duration of the run.

For **agent workflows** (VS Code Copilot, GitHub Copilot coding agent) state
is persisted to Copilot's native ``session_store`` via SQL — see the agent
definitions in ``.github/copilot/agents/`` and the skill instructions in
``.github/skills/``.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from newsletter.sources.git_source import fetch as git_fetch


# ---------------------------------------------------------------------------
# Newsletter template helpers
# ---------------------------------------------------------------------------

def _fmt_merged(merged: list[str]) -> str:
    if not merged:
        return "_No branches were merged in this period._ 🕊️"
    return "\n".join(f"- ✅ `{b}`" for b in merged)


def _fmt_branches(activity: list[dict[str, Any]], period_days: int) -> str:
    lines = [
        f"- {'🌿' if b['name'].startswith('release') else '🔨'} "
        f"**`{b['name']}`** — {b['commits_in_period']} commit(s) in the last "
        f"{period_days} day(s). Last commit by *{b['last_author']}* "
        f"({b['last_commit_timestamp'][:10]})."
        for b in activity
        if b.get("commits_in_period", 0) > 0
    ]
    return "\n".join(lines) if lines else "_No active branches in this period._ 🤫"


def _fmt_stale(stale: list[dict[str, Any]]) -> str:
    if not stale:
        return "_No stale branches detected._ 🎉"
    return "\n".join(
        f"- ⚠️ **`{b['name']}`** — last activity {b['age_days']} days ago "
        f"by *{b['last_author']}* ({b['last_commit_timestamp'][:10]}). "
        "Consider merging or deleting."
        for b in stale
    )


def _fmt_commits(commits: list[dict[str, Any]]) -> str:
    if not commits:
        return "_No commits found in this period._ 🕊️"
    lines = [
        f"- 🔹 `{c['short_sha']}` **{c['message'].splitlines()[0][:80]}** "
        f"— *{c['author_name']}* ({c['timestamp'][:10]})"
        for c in commits[:20]
    ]
    if len(commits) > 20:
        lines.append(f"- … and {len(commits) - 20} more commit(s).")
    return "\n".join(lines)


_TEMPLATE = """\
---
title: "{repo} Dev Digest — {date_range}"
period_days: {period_days}
repo: "{repo}"
branch: "{branch}"
generated_at: "{generated_at}"
---

# 📰 {repo} Dev Digest

> *Covering the last {period_days} day(s) of activity on `{branch}`.*

---

## 🚀 Newly Shipped (merged to {branch})

{merged_section}

---

## 🌿 Release Branches

{release_section}

---

## 🔨 Development Branches

{dev_section}

---

## 🕸️ Stale Branches

{stale_section}

---

*Generated by the git-newsletter editor • {generated_at}*
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def run(
    repo_path: str,
    branch: str = "main",
    period_days: int = 7,
    stale_after_days: int = 30,
    output_path: str = "newsletter_output.md",
) -> str:
    """
    Run the CLI newsletter pipeline for *repo_path* and return the generated
    Markdown as a string.  The Markdown is also written to *output_path*.

    Both local paths and remote URLs are accepted for *repo_path*.
    """
    git_data = git_fetch(repo_path, branch, period_days, stale_after_days)

    now = datetime.now(timezone.utc)
    from_dt = now - timedelta(days=period_days)
    date_range = f"{from_dt.strftime('%b %d')} – {now.strftime('%b %d, %Y')}"
    repo_display = Path(repo_path).name or repo_path

    release_branches = [
        b for b in git_data["branch_activity"]
        if b["name"].startswith("release")
    ]
    dev_branches = [
        b for b in git_data["branch_activity"]
        if not b["name"].startswith("release") and b["name"] != branch
    ]

    newsletter_md = _TEMPLATE.format(
        repo=repo_display,
        date_range=date_range,
        period_days=period_days,
        branch=branch,
        generated_at=now.isoformat(),
        merged_section=_fmt_merged(git_data["merged_branches"]),
        release_section=_fmt_branches(release_branches, period_days),
        dev_section=(
            _fmt_commits(git_data["commits"])
            + "\n\n"
            + _fmt_branches(dev_branches, period_days)
        ),
        stale_section=_fmt_stale(git_data["stale_branches"]),
    )

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(newsletter_md, encoding="utf-8")

    return newsletter_md
